# Generated by Django 4.0.2 on 2022-02-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nume')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categorii',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nume')),
                ('weight', models.CharField(max_length=20, verbose_name='Gramaj')),
                ('unit', models.CharField(max_length=10, verbose_name='U.M.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.category')),
            ],
            options={
                'verbose_name': 'produs',
                'verbose_name_plural': 'produse',
            },
        ),
    ]
