# Generated by Django 4.0.2 on 2022-02-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Tip Canal')),
            ],
            options={
                'verbose_name': 'Canal de distributie',
                'verbose_name_plural': 'Canale de distributie',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Zona')),
                ('area', models.CharField(max_length=10, verbose_name='Regiunea')),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zone',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'gama', 'verbose_name_plural': 'game'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.category', verbose_name='gama'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Numele')),
                ('CUI', models.IntegerField(blank=True, verbose_name='CUI')),
                ('distributor', models.BooleanField(blank=True, verbose_name='Distribuitor')),
                ('lka', models.BooleanField(blank=True, verbose_name='Local Key Accout')),
                ('address', models.CharField(blank=True, max_length=254, verbose_name='Adresa')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Localitatea')),
                ('contact_person', models.CharField(blank=True, max_length=254, verbose_name='Persoana de contact')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=25, verbose_name='Email')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.channel', verbose_name='Canal distributie')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clienti',
            },
        ),
    ]
