# Generated by Django 4.0.2 on 2022-04-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekplan',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
