# Generated by Django 4.0.2 on 2022-02-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_channel_zone_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing',
            field=models.CharField(blank=True, max_length=25, verbose_name='Ambalaj'),
        ),
    ]
