# Generated by Django 4.0.2 on 2022-04-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_weekplan_end_date_alter_weekplan_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekplan',
            name='week_num',
        ),
    ]
