# Generated by Django 4.0.2 on 2022-04-22 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_weekplan_week_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='sales.client'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='sales.shop'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
