# Generated by Django 4.0.2 on 2022-04-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_visit_client_alter_visit_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='shelf_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.agent'),
        ),
    ]
