# Generated by Django 4.0.2 on 2022-02-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_agent_county_shop_alter_channel_options_visit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'magazin', 'verbose_name_plural': 'magazine'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'vizita', 'verbose_name_plural': 'vizite'},
        ),
    ]
