# Generated by Django 4.0.2 on 2022-02-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_shop_options_alter_visit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'ASS', 'verbose_name_plural': 'ASSi'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'canal', 'verbose_name_plural': 'canale'},
        ),
        migrations.AddField(
            model_name='county',
            name='name',
            field=models.CharField(default='ALBA', max_length=50, verbose_name='Județ'),
        ),
    ]
