# Generated by Django 4.0.2 on 2022-04-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_visit_shelf_image_alter_weekplan_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='week_num',
        ),
    ]
