# Generated by Django 4.0.2 on 2022-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_agent_options_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CUI',
            field=models.IntegerField(blank=True, null=True, verbose_name='CUI'),
        ),
    ]
