# Generated by Django 4.0.2 on 2022-04-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_visit_week_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
