# Generated by Django 4.0.2 on 2022-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_client_cui'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_position',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Functia'),
        ),
        migrations.AddField(
            model_name='client',
            name='loc_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Numele locatiei'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
    ]
