# Generated by Django 4.0.2 on 2022-02-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_client_contact_position_client_loc_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipul')),
                ('short', models.CharField(blank=True, max_length=2, null=True, verbose_name='Prescurtat')),
            ],
            options={
                'verbose_name': 'categorie magazin',
                'verbose_name_plural': 'categorii magazine',
            },
        ),
    ]
