# Generated by Django 4.0.2 on 2022-02-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_shoptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.shoptype'),
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='short',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Prescurtat'),
        ),
    ]
