# Generated by Django 4.0.2 on 2022-02-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_shop_shop_type_alter_shoptype_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPresence',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.product')),
            ],
            bases=('sales.product',),
        ),
    ]
