# Generated by Django 4.0.2 on 2022-03-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_showpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_shelf', models.BooleanField(blank=True, default=False, verbose_name='La raft')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ShowPresence',
        ),
        migrations.AddField(
            model_name='visit',
            name='presence',
            field=models.ManyToManyField(blank=True, null=True, to='sales.Presence'),
        ),
    ]
