# Generated by Django 4.0.2 on 2022-03-04 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_visit_date_visit_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='shelf_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
