# Generated by Django 4.0.2 on 2022-03-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_visit_date_created_weekplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekplan',
            options={'verbose_name': 'plan saptamanal', 'verbose_name_plural': 'planuri saptamanale'},
        ),
    ]
