# Generated by Django 4.0.2 on 2022-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_weekplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekplan',
            name='week_num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
