# Generated by Django 4.0.2 on 2022-02-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'departament', 'verbose_name_plural': 'departamente'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'locatie', 'verbose_name_plural': 'locatii'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilizator', 'verbose_name_plural': 'utilizatori'},
        ),
    ]
