# Generated by Django 4.0.2 on 2022-06-15 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ASS',
                'verbose_name_plural': 'ASSi',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nume')),
            ],
            options={
                'verbose_name': 'gama',
                'verbose_name_plural': 'game',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Tip Canal')),
            ],
            options={
                'verbose_name': 'canal',
                'verbose_name_plural': 'canale',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Numele')),
                ('loc_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Numele locatiei')),
                ('CUI', models.IntegerField(blank=True, null=True, verbose_name='CUI')),
                ('distributor', models.BooleanField(blank=True, verbose_name='Distribuitor')),
                ('lka', models.BooleanField(blank=True, verbose_name='Local Key Accout')),
                ('address', models.CharField(blank=True, max_length=254, verbose_name='Adresa')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Localitatea')),
                ('contact_person', models.CharField(blank=True, max_length=254, verbose_name='Persoana de contact')),
                ('contact_position', models.CharField(blank=True, max_length=254, null=True, verbose_name='Functia')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.channel', verbose_name='Canal distributie')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clienti',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ALBA', max_length=50, verbose_name='Județ')),
                ('area', models.CharField(max_length=10, verbose_name='Regiunea')),
            ],
            options={
                'verbose_name': 'județ',
                'verbose_name_plural': 'județe',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nume')),
                ('weight', models.CharField(max_length=20, verbose_name='Gramaj')),
                ('unit', models.CharField(max_length=10, verbose_name='U.M.')),
                ('packing', models.CharField(blank=True, max_length=25, verbose_name='Ambalaj')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.category', verbose_name='gama')),
            ],
            options={
                'verbose_name': 'produs',
                'verbose_name_plural': 'produse',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Numele')),
                ('address', models.CharField(blank=True, max_length=254, verbose_name='Adresa')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Localitatea')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.county')),
            ],
            options={
                'verbose_name': 'magazin',
                'verbose_name_plural': 'magazine',
            },
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipul')),
                ('short', models.CharField(blank=True, max_length=3, null=True, verbose_name='Prescurtat')),
            ],
            options={
                'verbose_name': 'categorie magazin',
                'verbose_name_plural': 'categorii magazine',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Zona')),
                ('area', models.CharField(max_length=10, verbose_name='Regiunea')),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zone',
            },
        ),
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('date_created', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('monday_goal', models.TextField(blank=True)),
                ('monday_achieved', models.TextField(blank=True)),
                ('tuesday_goal', models.TextField(blank=True)),
                ('tuesday_achieved', models.TextField(blank=True)),
                ('wendsday_goal', models.TextField(blank=True)),
                ('wendsday_achieved', models.TextField(blank=True)),
                ('thursday_goal', models.TextField(blank=True)),
                ('thursday_achieved', models.TextField(blank=True)),
                ('friday_goal', models.TextField(blank=True)),
                ('friday_achieved', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.agent')),
                ('friday_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_location', to='sales.county')),
                ('monday_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_location', to='sales.county')),
                ('thursday_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_location', to='sales.county')),
                ('tuesday_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_location', to='sales.county')),
                ('wendsday_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wendsday_location', to='sales.county')),
            ],
            options={
                'verbose_name': 'plan saptamanal',
                'verbose_name_plural': 'planuri saptamanale',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('shelf_image', models.ImageField(blank=True, upload_to='images/')),
                ('quantity_ordered', models.IntegerField(blank=True, null=True, verbose_name='Baxuri comandate')),
                ('observations', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='sales.client')),
                ('products', models.ManyToManyField(related_name='products', to='sales.Product')),
                ('products_ordered', models.ManyToManyField(related_name='products_ordered', to='sales.Product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='sales.shop')),
            ],
            options={
                'verbose_name': 'vizita',
                'verbose_name_plural': 'vizite',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.shoptype'),
        ),
        migrations.AddField(
            model_name='county',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.zone'),
        ),
        migrations.AddField(
            model_name='client',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.county'),
        ),
        migrations.AddField(
            model_name='client',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.zone', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='agent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.zone'),
        ),
    ]
