# Generated by Django 4.0.2 on 2022-06-17 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nume produs')),
                ('weight', models.CharField(max_length=20, verbose_name='Gramaj')),
                ('unit', models.CharField(max_length=10, verbose_name='U.M.')),
                ('packing', models.CharField(blank=True, max_length=25, verbose_name='Ambalaj')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('producer', models.CharField(max_length=150, verbose_name='Producator')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.category', verbose_name='gama')),
            ],
            options={
                'verbose_name': 'produs concurenta',
                'verbose_name_plural': 'produse concurenta',
            },
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('price_value', models.FloatField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceinfo_client', to='sales.client')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceinfo_shop', to='sales.shop')),
            ],
        ),
    ]
