# Generated by Django 4.0.2 on 2022-06-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_priceentry_agent_priceentry_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceentry',
            name='price_value',
            field=models.FloatField(null=True),
        ),
    ]
