# Generated by Django 4.0.2 on 2022-06-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_productinfo_priceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Producator')),
            ],
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.producer', verbose_name='producator'),
        ),
    ]
