# Generated by Django 4.0.2 on 2022-05-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_weekplan_end_date_alter_weekplan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='products_ordered',
            field=models.ManyToManyField(related_name='products_ordered', to='sales.Product'),
        ),
        migrations.AddField(
            model_name='visit',
            name='quantity_ordered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Baxuri comandate'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='products',
            field=models.ManyToManyField(related_name='products', to='sales.Product'),
        ),
    ]
