# Generated by Django 4.0.2 on 2022-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_priceentry_price_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceentry',
            name='price_value',
            field=models.FloatField(default=0, null=True),
        ),
    ]
