# Generated by Django 4.0.2 on 2022-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_priceentry_price_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
