# Generated by Django 4.0.2 on 2022-06-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_visit_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clienți'},
        ),
        migrations.AlterModelOptions(
            name='priceentry',
            options={'verbose_name': 'înregistrare preț', 'verbose_name_plural': 'înregistrări preț'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'produs concurență', 'verbose_name_plural': 'produse concurență'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'vizită', 'verbose_name_plural': 'vizite'},
        ),
        migrations.AlterModelOptions(
            name='weekplan',
            options={'verbose_name': 'plan săptămânal', 'verbose_name_plural': 'planuri săptămânale'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=254, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='client',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.channel', verbose_name='Canal distribuție'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_position',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Funcția'),
        ),
        migrations.AlterField(
            model_name='client',
            name='loc_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Numele locației'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Producător'),
        ),
    ]
